target "YBTool" do
    platform :ios, '8.0'
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'MBProgressHUD'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'Masonry'
    pod 'FDFullscreenPopGesture'
    pod 'BlocksKit'
end

